= Паттерн visitor
:icons: font

== Введение

IMPORTANT: Всё что написано здесь -- попытка объяснить шаблон немного с другой стороны, а именно показать, когда он нужен в Java, и почему в нём нет смысла в некоторых других языках

Предположим, что у нас имеются:

. Иерархия типов
. Класс, способный делать что-то с каждым из классов иерархии

[NOTE]
====
Все примеры кода доступны в репозитории https://github.com/cac03/visitor-demo[`visitor-demo`]
====

=== Иерархия типов

.https://github.com/cac03/visitor-demo/blob/main/src/main/java/com/caco3/visitor/java/unvisited/Any.java[`Any.java`]
[source,java]
----
public interface Any {
    class Ghost implements Any {
    }

    class Flower implements Any {
    }

    class Unicorn implements Any {
    }
}
----

3 класса: `Ghost`, `Flower`, `Unicorn`, каждый из них реализует интерфейс `Any`.

=== Универсальный класс

Задача _универсального класса_ -- уметь показывать тип каждого объекта, реализующего интерфейс `Any` и Emoji, соответствующую ему.

.https://github.com/cac03/visitor-demo/blob/main/src/main/java/com/caco3/visitor/java/unvisited/Printer.java[`Printer.java`]
[source,java]
----
public class Printer {
    public void print(Any any) {
        System.out.println("❓ - Any");
    }

    public void print(Ghost ghost) {
        System.out.println("👻 - Ghost");
    }

    public void print(Flower flower) {
        System.out.println("🌺 - Flower");
    }

    public void print(Unicorn unicorn) {
        System.out.println("🦄 - Unicorn");
    }
}
----

Класс `Printer` имеет четыре перегрузки метода `print`:

* Одна из них принимает `Any` и выводит вопросительный знак
* Остальные три -- для конкретных классов, реализующих данный интерфейс

=== `main`

Добавим метод `main` в тот же класс:

.`Printer.java`
[source,java]
----
public class Printer {
    // ...

    public static void main(String[] args) {
        // <1>
        List<Any> list = List.of(
                new Ghost(),
                new Flower(),
                new Unicorn()
        );

        // <2>
        Printer printer = new Printer();

        for (Any any : list) {
            // <3>
            printer.print(any);
        }
    }
}
----
<1> создается список `Any`, который на самом деле содержит привидение, цветок и единорога
<2> создаётся экземпляр класса `Printer`
<3> для каждого элемента списка вызывается метод `print` класса `Printer`

Тут возникает главный вопрос: _**а что выведется, если это запустить?**_

А вывод будет следующим:

[source,text]
----
❓ - Any
❓ - Any
❓ - Any
----

В данном случае выводятся 3 вопросительных знака, потому что в Java выбор _конкретной_ перегрузки метода происходит *на этапе компиляции*.
А т.к. тип переменной `any` в (3) -- `Any`, компилятор выберет перегрузку метода, принимающую тип `Any`.

NOTE: Данный механизм известен, как https://en.wikipedia.org/wiki/Dynamic_dispatch#Single_and_multiple_dispatch[Single dynamic dispatch]: выбор метода происходит *динамически*, но выбор этого метода зависит только от одного атрибута: _настоящего типа_, на котором вызывается метод. Для этого используются https://en.wikipedia.org/wiki/Virtual_function[виртуальные методы]

=== Возьмём Groovy

*Groovy* -- язык программирования, способный запускаться на Java платформе.

Если мы попробуем запустить тот же пример на нём, то вывод будет другим:

[source,text]
----
👻 - Ghost
🌺 - Flower
🦄 - Unicorn
----

_Исходный код: https://github.com/cac03/visitor-demo/blob/main/src/main/groovy/com/caco3/visitor/groovy/Any.groovy[`Any.groovy`]
и https://github.com/cac03/visitor-demo/blob/main/src/main/groovy/com/caco3/visitor/groovy/Printer.groovy[`Printer.groovy`]_

Это происходит, потому что, в отличие от Java, Groovy -- **динамический**footnote:[Если не отключать динамизм в Groovy, например, с помощью https://docs.groovy-lang.org/latest/html/gapi/groovy/transform/CompileStatic.html[`@CompileStatic`]] язык.
Выбор конкретного метода зависит в нём _не только_ от типа, на котором метод вызывается, но и от других атрибутов -- типов параметров.

NOTE: По-умному это называется https://en.wikipedia.org/wiki/Multiple_dispatch[Multiple dispatch]

В документации Groovy это описано в:

. В сравнении с Java в разделе https://groovy-lang.org/differences.html#_multi_methods[Multi-methods]
. https://groovy-lang.org/objectorientation.html#_methods[В разделе, посвященном методам]

А сам алгоритм выбора метода для вызова описан https://groovy-lang.org/objectorientation.html#_method_selection_algorithm[здесь].

=== А если хочется так же в Java?

Для этого предлагается использовать паттерн visitor: он _позволяет_ эмулировать динамизм такого рода.

== Шаблон

Чтобы воспользоваться этим шаблоном, необходимо:

. Создать интерфейс `+++*+++Visitor` и объявить в нём методы для каждого конкретного подтипа
. Добавить метод `accept` в общий для всех интересующих нас подтипов тип
. Реализовать метод `accept` так, чтобы он вызывал нужный метод интерфейса `+++*+++Visitor`, передавая в него `this`
. Воспользоваться всем написанным ранее

WARNING: `+++*+++Visitor` -- необязательно интерфейс в смысле ключевого слова `interface`, это может быть и `class` / `abstract class`

_Звучит сложно, лучше рассмотреть пример._

=== Пример

==== Шаг 1. Создать интерфейс `+++*+++Visitor`

И объявить в нём методы для каждого конкретного подтипа:

.https://github.com/cac03/visitor-demo/blob/main/src/main/java/com/caco3/visitor/java/visitor/AnyVisitor.java[`AnyVisitor.java`]
[source,java]
----
public interface AnyVisitor {
    void visitGhost(Ghost ghost);

    void visitFlower(Flower flower);

    void visitUnicorn(Unicorn unicorn);
}
----

Для каждого типа объявлен метод `visit`, принимающий данный конкретный подтип.

==== Шаг 2. Добавить метод `accept` к общему типу

Тут всё просто: необходимо объявить метод `accept`, принимающий созданный ранее `AnyVisitor`:

.https://github.com/cac03/visitor-demo/blob/main/src/main/java/com/caco3/visitor/java/visitor/Any.java[`Any.java`]
[source,java]
----
public interface Any {
    void accept(AnyVisitor anyVisitor);
}
----

==== Шаг 3. Реализация метода `accept`

Тут тоже всё просто: в каждом конкретном подтипе необходимо переопределить метод `accept`, вызвав правильный метод интерфейса `AnyVisitor`:

* Для `Flower`:
+
[source,java]
----
class Flower implements Any {
    @Override
    public void accept(AnyVisitor anyVisitor) {
        anyVisitor.visitFlower(this);
    }
}
----
* Для `Ghost`:
+
[source,java]
----
class Ghost implements Any {
    @Override
    public void accept(AnyVisitor anyVisitor) {
        anyVisitor.visitGhost(this);
    }
}
----
* Для `Unicorn`:
+
[source,java]
----
class Unicorn implements Any {
    @Override
    public void accept(AnyVisitor anyVisitor) {
        anyVisitor.visitUnicorn(this);
    }
}
----

==== Шаг 4. Связывание всего воедино

Остаётся только правильно воспользоваться всем написанным.

==== `Printer`

Сперва изменим класс `Printer` так, чтобы он реализовывал интерфейс `AnyVisitor`:

.https://github.com/cac03/visitor-demo/blob/main/src/main/java/com/caco3/visitor/java/visitor/Printer.java[`Printer.java`]
[source,java]
----
public class Printer implements AnyVisitor {
    @Override
    public void visitGhost(Ghost ghost) {
        System.out.println("👻 - Ghost");
    }

    @Override
    public void visitFlower(Flower flower) {
        System.out.println("🌺 - Flower");
    }

    @Override
    public void visitUnicorn(Unicorn unicorn) {
        System.out.println("🦄 - Unicorn");
    }
}
----

В каждом из методов `visit+++*+++` `Printer` выводит Emoji и имя типа.

==== `main`

А в методе `main` теперь необходимо вызывать метод `accept` из интерфейса `Any`, передавая в него `Printer`:

[source,java]
----
public class Printer {
    public static void main(String[] args) {
        List<Any> list = List.of(
                new Ghost(),
                new Flower(),
                new Unicorn()
        );

        Printer printer = new Printer();

        for (Any any : list) {
            // Вот здесь
            any.accept(printer);
        }
    }
}
----

И тогда программа, наконец, выведет:

[source,text]
----
👻 - Ghost
🌺 - Flower
🦄 - Unicorn
----

== По-научному

Шаблон visitor позволяет отделить алгоритм от классов, над которыми он оперирует.

_В примере выше алгоритм выводит Emoji и тип в консоль._

Такая организация классов в программе позволяет добавлять новые _алгоритмы_, не изменяя сами классы, с которыми данный алгоритм работает.

[NOTE]
====
В основе данного шаблона -- механизм, называемый https://en.wikipedia.org/wiki/Double_dispatch[Double dispatch]: выбор нужного _виртуального_ метода происходит дважды:

. В `main`: `any.accept(visitor)`
. В переопределенных методах `accept(AnyVisitor)` конкретных реализаций интерфейса `Any`
====

== Где используется?

* https://asm.ow2.io/javadoc/org/objectweb/asm/ClassVisitor.html[`ClassVisitor`] из https://asm.ow2.io/[ASM] -- библиотеки манипуляции байт-кодом Java
* https://docs.oracle.com/javase/7/docs/jdk/api/javac/tree/com/sun/source/tree/TreeVisitor.html[`TreeVisitor`] из `javac` -- компилятора Java

== Когда использовать?

Тогда, когда:

* Число структур данных _редко меняется_ (как в примере выше)
* Постоянно добавляются *новые алгоритмы* их обработки

== Итог

* Visitor отделяет алгоритм от классов, над которыми он оперирует
* Организация кода, предлагаемая шаблоном, необходима не во всех языках: в некоторых это поведение доступно "из коробки"
