:experimental:

= Intellij IDEA. Советы

== Запуск и отладка

* kbd:[Ctrl + Shift + F10] -- запустить в контексте.
** Если курсор стоит в методе `main`, то сочетание клавиш запустит его
** В тестовом методе оно запустит тестовый метод, а в тестовом классе -- все тесты этого класса

== Как создать переменную?

. Написать правую часть.
. Ввести переменную: kbd:[Ctrl + Alt + V].

== Alt + Enter

kbd:[Alt + Enter] -- вывести список доступных _здесь_ действий.
Если не знаете, что нужно сделать или что хочется сделать, то используйте kbd:[Alt + Enter]: IDEA постарается угадать.

== Навигация

* kbd:[Alt + F1] -- открыть или показать окно "Project".
* kbd:[Ctrl + B] -- перейти к определению:
** если курсор указывает на класс, открыть класс
** на метод -- исходный код метода
* kbd:[Ctrl + U] -- перейти к определению предка: метода, класса, интерфейса
* kbd:[Ctrl + N] -- Поиск классов
* kbd:[Ctrl + E] -- Недавние файлы
* kbd:[F2] -- перейти к следующей ошибке
* kbd:[Ctrl + Alt + B] -- перейти к реализациям: методов, интерфейсов или наследникам класса

== Рефакторинг

*Рефакторинг* -- изменение внутренней структуры кода без изменения его поведения

* переименовать переменную, класс, метод
* добавить вспомогательный метод
* удалить метод

'''

* kbd:[Shift + F6] -- переименовать.
Если курсор стоит на имени класса, то переименовать класс, на имени метода -- метод и т.д.
* kbd:[Ctrl + Alt + M] -- вынести выбранный участок кода в отдельный метод
* kbd:[Ctrl + Alt + N] -- удалить метод или переменную и встроить её использование
* kbd:[Ctrl + Alt + L] -- отформатировать код: расставить пробелы, убрать лишние пусты строки
* kbd:[Ctrl + Alt + O] -- удалить неиспользуемые ``import``ы

== Поиск

* kbd:[Ctrl + F] -- поиск в _текущем файле_.
Работает так же, как в браузере.
* kbd:[Ctrl + Shift + F] -- найти текст глобально: в проекте, сторонних библиотеках
* kbd:[Ctrl + N] -- поиск класса
* kbd:[Alt + F7] -- найти места, где используется то, куда указывает курсор: метод, переменная, класс

== Выделение

* kbd:[Ctrl + W] -- расширить выделение
* kbd:[Ctrl + Shift + W] -- сузить выделение

WARNING: kbd:[Ctrl + W] в других программах обычно что-то закрывает: Firefox закрывает текущую вкладку, kbd:[Ctrl + Shift + T] открывает её заново

== Генерация кода

* kbd:[Alt + Insert] -- сгенерировать в зависимости от контекста:
** В окне "Project" -- создать класс, интерфейс, `enum`
** В классе -- сгенерировать геттеры и сеттеры, конструкторы, `equals` и `hashCode`, `toString`
** В тестовом классе -- тестовый метод, метод `setUp` или `tearDown`

== Прочее

* kbd:[Ctrl + Shift + Enter] -- закончить выражение и перейти на следующую строку.
Сочетание клавиш отформатирует текущую строку, добавит точку с запятой, если её нет.
* kbd:[Ctrl + Alt + T] -- обернуть выбранный участок кода, например в `if`, или `try`-`finally`
