= Глобальная установка JDK

Если вы установите JDK глобально, то:

. JDK будет доступна всем пользователям
. Другие программы, запускающиеся на Java-платформе, будут использовать глобально установленную версию

== Как установить

Общий для всех операционных систем способ:

. Перейти на сайт поставщика
. Следовать его инструкциям

Однако, не на всех операционных системах такой подход является традиционным:

* на Linux программы устанавливают с помощью пакетных менеджеров
* на Mac часто используют `brew`,

поэтому посмотрите разделы, специфичные для каждой из операционных систем: <<windows>>, <<linux>>, <<mac>>

[#windows]
=== Windows

Если у вас Windows, то, скорее всего, вам будет привычнее скачать установочный файл с сайта.
Вы можете установить <<oracle-jdk,Oracle JDK>> или <<openjdk-builds,другую сборку>>.

Функционально они одинаковы

[#linux]
=== Linux

Если у Вас *Linux*, посмотрите, доступен ли JDK в репозиториях дистрибутива.

* На Ubuntu JDK можно установить так:
+
[source,shell script]
----
# apt-get install openjdk-11-jdk
----
* На Arch Linux и основанных на нём дистрибутивах, например, Manjaro:
+
[source,shell script]
----
# pacman -S jdk11-openjdk
----
* Если у вас другой дистрибутив, то посмотрите в Google 🙄

[#mac]
=== Mac

Если у вас Mac и Вы используете `brew`, то посмотрите эти статьи:

* https://medium.com/macoclock/using-homebrew-to-install-java-jdk11-on-macos-44b30f497b38[Using HomeBrew to Install Java JDK11 on macOS]
* https://mkyong.com/java/how-to-install-java-on-mac-osx/[How to install Java JDK on macOS]

== JDK

[#oracle-jdk]
=== Oracle JDK

https://www.oracle.com/java/technologies/javase-jdk11-downloads.html[Oracle JDK] -- скачать, установить

* Требуется регистрация
* Бесплатна для разработки и персонального использования.
См. также:
** https://www.oracle.com/java/technologies/javase/jdk-faqs.html[Oracle Java SE Licensing FAQ]
** https://habr.com/ru/post/448632/[Java теперь платная? Развенчиваем слухи (или нет?)]

[#openjdk-builds]
=== Сборки OpenJDK

* https://adoptium.net/index.html[Eclipse Temurin] (бывший AdoptOpenJDK)
* https://bell-sw.com/[Liberica JDK]
* https://www.azul.com/downloads/?package=jdk#download-openjdk[Azul Zulu]
