= Глобальная установка JDK

Если установить JDK глобально, то:

. JDK будет доступна всем пользователям компьютера
. Другие программы, запускающиеся на Java-платформе, будут использовать глобально установленную версию

== Как установить

Способ для всех операционных систем:

. Перейти на сайт поставщика
. Следовать инструкциям 🙄

Однако, не во всех операционных системах принят такой подход:

* на Linux программы устанавливают с помощью пакетных менеджеров
* на Mac часто используют `brew`,

поэтому посмотрите разделы, специфичные для каждой из операционных систем: <<windows>>, <<linux>>, <<mac>>

[#windows]
=== Windows

Если у вас Windows, то, скорее всего, вам будет привычнее скачать установочный файл с сайта.
Вы можете установить <<oracle-jdk,Oracle JDK>> или <<openjdk-builds,другую сборку>>.

Функционально они одинаковы

[#linux]
=== Linux

Если у Вас *Linux*, посмотрите, доступен ли JDK в репозиториях дистрибутива.

* На Ubuntu JDK можно установить так:
+
[source,shell script]
----
# apt-get install openjdk-11-jdk
----
* На Arch Linux и основанных на нём дистрибутивах, например, Manjaro:
+
[source,shell script]
----
# pacman -S jdk11-openjdk
----
* Если у вас другой дистрибутив, то посмотрите в Google 🙄

[#mac]
=== Mac

Если у вас Mac и Вы используете `brew`, то посмотрите эти статьи:

* https://medium.com/macoclock/using-homebrew-to-install-java-jdk11-on-macos-44b30f497b38[Using HomeBrew to Install Java JDK11 on macOS]
* https://mkyong.com/java/how-to-install-java-on-mac-osx/[How to install Java JDK on macOS]

== JDK

[#oracle-jdk]
=== Oracle JDK

https://www.oracle.com/java/technologies/downloads/[JDK от Oracle] -- скачать, установить

[#openjdk-builds]
=== Сборки OpenJDK

* https://adoptium.net/index.html[Eclipse Temurin] (бывший AdoptOpenJDK)
* https://bell-sw.com/[Liberica JDK]
* https://www.azul.com/downloads/?package=jdk#download-openjdk[Azul Zulu]
